// Command gen-openapi generates openapi/openapi.yaml from openapi/routes.yaml.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

type routesFile struct {
	Routes []routeDef `yaml:"routes"`
}

type routeDef struct {
	Path     string     `yaml:"path"`
	Methods  []string   `yaml:"methods"`
	Tag      string     `yaml:"tag"`
	Summary  string     `yaml:"summary"`
	Security string     `yaml:"security"`
	Params   []paramDef `yaml:"params,omitempty"`
}

type paramDef struct {
	Name        string      `yaml:"name"`
	In          string      `yaml:"in"`
	Type        string      `yaml:"type"`
	Format      string      `yaml:"format,omitempty"`
	Description string      `yaml:"description,omitempty"`
	Example     interface{} `yaml:"example,omitempty"`
	Required    *bool       `yaml:"required,omitempty"`
}

var pathParamPattern = regexp.MustCompile(`\{([^}]+)\}`)

type openAPISpec struct {
	OpenAPI    string                 `yaml:"openapi"`
	Info       map[string]interface{} `yaml:"info"`
	Servers    []map[string]string    `yaml:"servers"`
	Tags       []map[string]string    `yaml:"tags"`
	Paths      map[string]interface{} `yaml:"paths"`
	Components map[string]interface{} `yaml:"components"`
}

func main() {
	root := findRepoRoot()
	routesPath := filepath.Join(root, "openapi", "routes.yaml")
	outPath := filepath.Join(root, "openapi", "openapi.yaml")

	data, err := os.ReadFile(routesPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "read routes: %v\n", err)
		os.Exit(1)
	}

	var routes routesFile
	if err := yaml.Unmarshal(data, &routes); err != nil {
		fmt.Fprintf(os.Stderr, "parse routes: %v\n", err)
		os.Exit(1)
	}

	spec := buildSpec(routes.Routes)
	out, err := yaml.Marshal(spec)
	if err != nil {
		fmt.Fprintf(os.Stderr, "marshal spec: %v\n", err)
		os.Exit(1)
	}

	header := "# Generated by scripts/gen-openapi — do not edit by hand.\n# Source: openapi/routes.yaml — regenerate with: make openapi\n\n"
	if err := os.WriteFile(outPath, append([]byte(header), out...), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "write spec: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d routes)\n", outPath, len(routes.Routes))
}

func findRepoRoot() string {
	if wd, err := os.Getwd(); err == nil {
		dir := wd
		for i := 0; i < 6; i++ {
			if _, err := os.Stat(filepath.Join(dir, "openapi", "routes.yaml")); err == nil {
				return dir
			}
			parent := filepath.Dir(dir)
			if parent == dir {
				break
			}
			dir = parent
		}
	}
	return "."
}

func buildSpec(routes []routeDef) openAPISpec {
	tagSet := map[string]struct{}{}
	paths := map[string]interface{}{}

	for _, route := range routes {
		tagSet[route.Tag] = struct{}{}
		pathItem, ok := paths[route.Path].(map[string]interface{})
		if !ok {
			pathItem = map[string]interface{}{}
			paths[route.Path] = pathItem
		}

		for _, method := range route.Methods {
			op := map[string]interface{}{
				"tags":        []string{route.Tag},
				"summary":     route.Summary,
				"operationId": operationID(route.Path, method),
				"responses": map[string]interface{}{
					"200": map[string]interface{}{
						"description": "Successful response",
					},
					"401": map[string]interface{}{
						"description": "Unauthenticated",
						"content": map[string]interface{}{
							"application/json": map[string]interface{}{
								"schema": map[string]string{"$ref": "#/components/schemas/Error"},
							},
						},
					},
					"422": map[string]interface{}{
						"description": "Validation error",
						"content": map[string]interface{}{
							"application/json": map[string]interface{}{
								"schema": map[string]string{"$ref": "#/components/schemas/ValidationError"},
							},
						},
					},
				},
			}

			if params := buildParameters(route); len(params) > 0 {
				op["parameters"] = params
			}

			if sec := securityRequirement(route.Security); sec != nil {
				op["security"] = sec
			}

			if methodNeedsBody(method) {
				op["requestBody"] = map[string]interface{}{
					"content": map[string]interface{}{
						"application/json": map[string]interface{}{
							"schema": map[string]string{"type": "object"},
						},
						"multipart/form-data": map[string]interface{}{
							"schema": map[string]string{"type": "object"},
						},
					},
				}
			}

			pathItem[strings.ToLower(method)] = op
		}
	}

	tags := make([]map[string]string, 0, len(tagSet))
	for tag := range tagSet {
		tags = append(tags, map[string]string{"name": tag})
	}
	sort.Slice(tags, func(i, j int) bool {
		return tags[i]["name"] < tags[j]["name"]
	})

	return openAPISpec{
		OpenAPI: "3.0.3",
		Info: map[string]interface{}{
			"title":       "MetaRGB API",
			"description": "REST API for MetaRGB microservices. Laravel-compatible JSON responses served via Kong → grpc-gateway → gRPC services.",
			"version":     "1.0.0",
			"contact": map[string]string{
				"name": "MetaRGB",
			},
		},
		Servers: []map[string]string{
			{"url": "http://localhost:8000", "description": "Kong API Gateway (local)"},
			{"url": "http://localhost:8080", "description": "grpc-gateway direct (dev)"},
		},
		Tags:  tags,
		Paths: paths,
		Components: map[string]interface{}{
			"securitySchemes": map[string]interface{}{
				"BearerAuth": map[string]interface{}{
					"type":         "http",
					"scheme":       "bearer",
					"bearerFormat": "Token",
					"description":  "Laravel Sanctum-style bearer token. Header: Authorization: Bearer {token}",
				},
			},
			"schemas": map[string]interface{}{
				"Error": map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"message": map[string]string{"type": "string"},
					},
				},
				"ValidationError": map[string]interface{}{
					"type": "object",
					"properties": map[string]interface{}{
						"message": map[string]string{"type": "string"},
						"errors": map[string]interface{}{
							"type": "object",
							"additionalProperties": map[string]interface{}{
								"type":  "array",
								"items": map[string]string{"type": "string"},
							},
						},
					},
				},
			},
		},
	}
}

func securityRequirement(security string) []map[string][]string {
	switch security {
	case "bearer", "verified_email":
		return []map[string][]string{{"BearerAuth": {}}}
	case "optional", "guest":
		return []map[string][]string{
			{},
			{"BearerAuth": {}},
		}
	default:
		return nil
	}
}

func methodNeedsBody(method string) bool {
	switch strings.ToLower(method) {
	case "post", "put", "patch":
		return true
	default:
		return false
	}
}

func operationID(path, method string) string {
	slug := strings.TrimPrefix(path, "/api/")
	slug = strings.ReplaceAll(slug, "/", "_")
	slug = strings.ReplaceAll(slug, "{", "")
	slug = strings.ReplaceAll(slug, "}", "")
	return fmt.Sprintf("%s_%s", strings.ToLower(method), slug)
}

func buildParameters(route routeDef) []map[string]interface{} {
	overrides := map[string]paramDef{}
	for _, p := range route.Params {
		overrides[p.Name] = p
	}

	names := extractPathParamNames(route.Path)
	params := make([]map[string]interface{}, 0, len(names))
	for _, name := range names {
		def := defaultPathParam(name)
		if override, ok := overrides[name]; ok {
			def = mergeParamDef(def, override)
		}
		params = append(params, def)
	}

	for _, p := range route.Params {
		if p.In == "query" {
			params = append(params, queryParameter(p))
		}
	}

	return params
}

func extractPathParamNames(path string) []string {
	matches := pathParamPattern.FindAllStringSubmatch(path, -1)
	if len(matches) == 0 {
		return nil
	}
	names := make([]string, 0, len(matches))
	for _, match := range matches {
		names = append(names, match[1])
	}
	return names
}

func defaultPathParam(name string) map[string]interface{} {
	paramType, format, example := inferParamSchema(name)
	schema := map[string]interface{}{
		"type": paramType,
	}
	if format != "" {
		schema["format"] = format
	}
	if example != nil {
		schema["example"] = example
	}

	return map[string]interface{}{
		"name":        name,
		"in":          "path",
		"required":    true,
		"description": pathParamDescription(name),
		"schema":      schema,
	}
}

func mergeParamDef(base map[string]interface{}, override paramDef) map[string]interface{} {
	result := map[string]interface{}{
		"name":     base["name"],
		"in":       "path",
		"required": true,
	}
	if override.In != "" {
		result["in"] = override.In
	}
	if override.Required != nil {
		result["required"] = *override.Required
	}
	if override.Description != "" {
		result["description"] = override.Description
	} else {
		result["description"] = base["description"]
	}

	schema := map[string]interface{}{}
	if baseSchema, ok := base["schema"].(map[string]interface{}); ok {
		for k, v := range baseSchema {
			schema[k] = v
		}
	}
	if override.Type != "" {
		schema["type"] = override.Type
	}
	if override.Format != "" {
		schema["format"] = override.Format
	}
	if override.Example != nil {
		schema["example"] = override.Example
	}
	result["schema"] = schema
	return result
}

func queryParameter(p paramDef) map[string]interface{} {
	paramType := p.Type
	if paramType == "" {
		paramType = "string"
	}
	required := false
	if p.Required != nil {
		required = *p.Required
	}
	schema := map[string]interface{}{"type": paramType}
	if p.Format != "" {
		schema["format"] = p.Format
	}
	if p.Example != nil {
		schema["example"] = p.Example
	}
	return map[string]interface{}{
		"name":        p.Name,
		"in":          "query",
		"required":    required,
		"description": p.Description,
		"schema":      schema,
	}
}

func inferParamSchema(name string) (paramType, format string, example interface{}) {
	switch name {
	case "id", "feature", "dynasty", "joinRequest", "recievedPrize", "family", "comment", "reply", "video":
		return "integer", "int64", 1
	case "buildingModel":
		return "string", "", "model-slug"
	case "slug", "code", "key", "path":
		return "string", "", "example-slug"
	case "user":
		return "string", "", "user-code"
	default:
		return "string", "", name
	}
}

func pathParamDescription(name string) string {
	descriptions := map[string]string{
		"id":            "Resource ID",
		"feature":       "Feature ID",
		"user":          "User ID or citizen code",
		"slug":          "URL slug",
		"code":          "Citizen code",
		"dynasty":       "Dynasty ID",
		"joinRequest":   "Join request ID",
		"recievedPrize": "Received prize ID",
		"family":        "Family ID",
		"comment":       "Comment ID",
		"reply":         "Reply ID",
		"video":         "Video slug or ID",
		"buildingModel": "Building model identifier",
		"key":           "Setting key",
		"path":          "File path under uploads",
	}
	if desc, ok := descriptions[name]; ok {
		return desc
	}
	return fmt.Sprintf("%s path parameter", name)
}
